# Generated by Django 2.0.1 on 2019-03-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='city',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='country',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='district',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='first_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='house_number',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='last_name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='phone',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='postcode',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='state',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='street',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
