# Generated by Django 2.0.1 on 2019-04-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190331_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='toevoegsel',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='house_number',
            field=models.PositiveIntegerField(),
        ),
    ]
