# Generated by Django 2.0.1 on 2019-02-22 10:21

from django.db import migrations, models
import prods.models


class Migration(migrations.Migration):

    dependencies = [
        ('prods', '0002_auto_20190221_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=prods.models.upload_img_file),
        ),
    ]
