# Generated by Django 2.0.1 on 2019-02-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prods', '0005_auto_20190225_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10000000),
        ),
    ]
