# Generated by Django 2.0.1 on 2019-03-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prods', '0007_cart_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000000),
        ),
    ]
